# Generated by Django 4.2.16 on 2024-10-26 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DisplaySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('vegetable', 'Vegetable Section'), ('main', 'Main Section'), ('bread', 'Bread Section')], max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='ingredients/')),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='menu_items/')),
            ],
        ),
        migrations.CreateModel(
            name='DailyDisplayAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('meal_period', models.CharField(choices=[('BL', 'Breakfast/Lunch'), ('D', 'Dinner')], max_length=2)),
                ('quantity', models.FloatField()),
                ('quantity_type', models.CharField(choices=[('g', 'Grams'), ('kg', 'Kilograms'), ('num', 'Numbers')], max_length=20)),
                ('display_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.displaysection')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.menuitem')),
            ],
        ),
    ]
